### ISSUE TITLE
Binding credentials API

### ISSUE THREAD

**Issue by nilebox** [kubernetes-sigs/service-catalog#1109]
Currently Binding provides the following API for storing credentials ([OSB spec](https://github.com/openservicebrokerapi/servicebroker/blob/master/spec.md#credentials)) returned by the broker:
```
apiVersion: servicecatalog.k8s.io/v1alpha1
kind: Binding
spec:
  secretName: my-secret
```
The `credentials` object then is treated as `map[string]interface{}` and each top-level key of this map becomes a `Secret` key with corresponding value stored as secret data.
While it provides nice UX for injecting each credential separately as an environment variable into Pod, it has some limitations:
1. As it was previously pointed in https://github.com/kubernetes-incubator/service-catalog/pull/1028#issuecomment-315869885, Secret key format is more restrictive than JSON property names. It means that if the broker returns credentials with `/` or `$` in the name, we will fail to store them.
2. As we store each serialized value separately, we can't tell what was the value type - string or JSON/number/array etc.
3. If the `credentials` object is more complicated than flat key-value pairs (`map[string]string`), the Secret data can't be injected as environment variables into Pods without extra manipulation.

We had similar discussions for Instance/Bindings parameters support (https://github.com/kubernetes-incubator/service-catalog/issues/1048 and https://github.com/kubernetes-incubator/service-catalog/issues/621), and resolved these limitations by adding support for a single Secret key storing the entire JSON payload as it is.
We can take the same approach for Binding credentials (but in the reverse direction, of course).

If we want to keep the current UX of easily injecting "simple" credentials, we can switch to a union type as we did for Instance/Bindings parameters. So the API could look like:
```
apiVersion: servicecatalog.k8s.io/v1alpha1
kind: Binding
spec:
  credentials:
    # either store as key-value pairs
    secretRef:
      name: my-secret
    # or store the raw credentials JSON object as a single blob
    secretKeyRef:
      name: my-secret
      key: credentials-blob
```
While I don't think this issue is urgent, it does have implications on breaking the API, and thus it could make sense to switch to the union type before we release beta (https://github.com/kubernetes-incubator/service-catalog/issues/1098).

**Comment by pmorie** [comment]
I do think that there are a number of use cases that would make it convenient to store the entire credentials blob from the server

**Comment by phil9909** [comment]
@nilebox We are facing the same problem currently. Could you work around it?

We would consider contributing a fix, if the broader community is interested.

> I do think that there are a number of use cases that would make it convenient to store the entire credentials blob from the server
> @pmorie 

We had something similar in mind.  Maybe something like:
```yaml
apiVersion: servicecatalog.k8s.io/v1beta1
kind: Binding
spec:
  secretName: my-secret
  secretKey: credentials
```
Would cause the controller to store the whole credentials object in the key `credentials` of the secret `my-secret`
