### ISSUE TITLE
Unable to patch ClusterServiceBroker relistRequests without access to secrets

### ISSUE THREAD

**Issue by prydonius** [kubernetes-sigs/service-catalog#1753]
The [Kubeapps dashboard](https://github.com/kubeapps/kubeapps) has a button that allows you to manually request a relisting for a ClusterServiceBroker. It does this by executing a PATCH on the ClusterServiceBroker resource, e.g.:

```
curl 'http://localhost:5000/api/kube/apis/servicecatalog.k8s.io/v1beta1/clusterservicebrokers/osba' -X PATCH --data-binary '{"spec":{"relistRequests":3}}'
```

Unfortunately, since this the ClusterServiceBroker spec includes a Secret reference, the above request will fail if the user or serviceaccount does not have permissions to list secrets. In Kubeapps, we use a serviceaccount to access the Kubernetes API and I'm trying to restrict the set of roles it has access to. Without access to Secrets, the API returns the following error:

```
clusterservicebrokers.servicecatalog.k8s.io \"osba\" is forbidden: broker forbidden access to auth secret (osba-open-service-broker-azure-auth)
```

Since Kubeapps doesn't know which namespaces an auth secret will be present in, the only way to make this work would be to give the serviceaccount cluster-level access to Secrets. This is obviously not great.

I'm not sure if this is a limitation of the way Kubernetes API servers work, or a bug in the Service Catalog API server implementation. Ideally, I should not have to have access to Secrets if I'm not changing the auth secret reference. Is there a way to do this today or is it possible to change the implementation to make this possible?

cc @arschles @ritazh @sozercan @evanlouie

**Comment by MHBauer** [comment]
Is the secret the auth config stuff? It seems weird to me that access to a reference in some object would require access to the object being referred to. I don't understand what's going on here.

**Comment by prydonius** [comment]
@MHBauer it is, yeah - this is the spec:

```
  spec:
    authInfo:
      basic:
        secretRef:
          name: osba-open-service-broker-azure-auth
          namespace: osba
    relistBehavior: Duration
    relistDuration: 15m0s
    relistRequests: 2
    url: http://osba-open-service-broker-azure.osba.svc.cluster.local
```

I agree, that it is pretty strange to validate that on create/update.
