### ISSUE TITLE
Document our resources schema / yaml

### ISSUE THREAD

**Issue by carolynvs** [kubernetes-sigs/service-catalog#1825]
It would be incredibly helpful to have a document that outlines the entire set of acceptable yaml that can be sent to Service Catalog, which fields are required, when you would set an optional value, etc.

For example:

**manifest-schema.md**
```yaml
apiVersion: servicecatalog.k8s.io/v1beta1
kind: ServiceInstance
metadata:
  name: ups-instance
  namespace: test-ns
spec:
  clusterServiceClassExternalName: user-provided-service # Required
  clusterServiceClassName: user-provided-service-uuid # Required (but explain that one must be set)
  clusterServicePlanExternalName: default # Required
  clusterServicePlanName: default-uuid #Required (but explain again when)
  parameters: # Optional
    param-1: value-1
    param-2: value-2
...
```

Maybe a full set to of values and a table explaining each one?
