### ISSUE TITLE
LastTransitionTime isn't updated when condition's reason changes, but the status remains unchanged

### ISSUE THREAD

**Issue by luksa** [kubernetes-sigs/service-catalog#1829]
Imagine a case where the ServiceInstance's Ready condition changes from this:
```
    conditions:
    - type: Ready
      status: "False"
      reason: ReferencesNonexistentServiceClass
      message: 'The instance references a ClusterServiceClass that does not exist.
        References a non-existent ClusterServiceClass (ExternalName: "user-provided-service")
        or there is more than one (found: 0)'
      lastTransitionTime: 2018-03-13T08:26:13Z
```
to this:      
```
    conditions:
    - type: Ready
      status: "False"
      reason: ReferencesNonexistentServicePlan
      message: 'The instance references a ClusterServicePlan that does not exist.
        References a non-existent ClusterServicePlan (K8S: "" ExternalName: "nonexistentplan")
        on ClusterServiceClass (K8S: "4f6e6cf6-ffdd-425f-a2c7-3c9258ad2468" ExternalName:
        "user-provided-service") or there is more than one (found: 0)'
      lastTransitionTime: 2018-03-13T08:26:13Z
```

The `lastTransitionTime` hasn't been updated, even though, from the user's perspective, the status as a whole _has_ changed (the underlying cause has changed). 

Do we want `lastTransitionTime` to behave like this? I'm feeling this may lead to users not noticing the change (either manually or programatically). 

I'm reporting this just so we're all aware of this and we have this behavior documented (at least here in the issue).
