### ISSUE TITLE
Explain how to vendor service catalog using dep

### ISSUE THREAD

**Issue by carolynvs** [kubernetes-sigs/service-catalog#1948]
It's pretty common for someone pulling in service catalog to also have a dependency that uses a different version of the client-go library. We should add a FAQ, or find some other appropriate place to highlight how to vendor us properly using dep.

**Gopkg.toml**

```toml
[[override]]
   name = "k8s.io/client-go"
   version = "INSERT_DESIRED_VERSION_HERE" # e.g. kubernetes-1.9.1
```

Then run `dep ensure` to apply the change the change.
