### ISSUE TITLE
The apiserver refuses to work when first etcd-server is not available.

### ISSUE THREAD

**Issue by chenlein** [kubernetes-sigs/service-catalog#2647]
# Bug Report 

**What happened**:
As the issue's title!

**What you expected to happen**:
The etcd **_cluster_** can be work, the apiserver should be work too!

**How to reproduce it (as minimally and precisely as possible)**:
I have a etcd cluster of three node, and i stoped the first node etcd-0:
```shell
[root@master-0 service-catalog]# alias
alias etcdctl='ETCDCTL_API=3 etcdctl --cacert /etc/etcd/pki/ca.pem --cert /etc/etcd/pki/client.pem --key /etc/etcd/pki/client-key.pem --endpoints=[etcd-0:2379,etcd-1:2379,etcd-2:2379]'

[root@master-0 service-catalog]# etcdctl member list -w table
+------------------+---------+--------+---------------------+---------------------+
|        ID        | STATUS  |  NAME  |     PEER ADDRS      |    CLIENT ADDRS     |
+------------------+---------+--------+---------------------+---------------------+
|  f0f92d99677353f | started | etcd-0 | https://etcd-0:2380 | https://etcd-0:2379 |
| 1a147ce6336081c1 | started | etcd-1 | https://etcd-1:2380 | https://etcd-1:2379 |
| ed2c681b974a3802 | started | etcd-2 | https://etcd-2:2380 | https://etcd-2:2379 |
+------------------+---------+--------+---------------------+---------------------+

[root@master-0 service-catalog]#  etcdctl endpoint status -w table
Failed to get the status of endpoint etcd-0:2379 (context deadline exceeded)
+-------------+------------------+---------+---------+-----------+-----------+------------+
|  ENDPOINT   |        ID        | VERSION | DB SIZE | IS LEADER | RAFT TERM | RAFT INDEX |
+-------------+------------------+---------+---------+-----------+-----------+------------+
| etcd-1:2379 | 1a147ce6336081c1 |  3.2.18 |   20 MB |      true |        19 |    2028364 |
| etcd-2:2379 | ed2c681b974a3802 |  3.2.18 |   20 MB |     false |        19 |    2028364 |
+-------------+------------------+---------+---------+-----------+-----------+------------+

```
And then, apiserver refuses to work:
```shell
[root@master-0 service-catalog]# kubectl get clusterservicebrokers.servicecatalog.k8s.io 
Error from server (Timeout): the server was unable to return a response in the time allotted, but may still be processing the request (get clusterservicebrokers.servicecatalog.k8s.io)

[root@master-0 service-catalog]# kubectl get pods -n ns-support 
NAME                                                READY   STATUS    RESTARTS   AGE
catalog-catalog-apiserver-8696574c4c-gn5rf          1/1     Running   0          7m52s
catalog-catalog-controller-manager-89f68bf9-flrpp   0/1     Running   0          6d1h

[root@master-0 service-catalog]# kubectl get cs
NAME                 STATUS      MESSAGE                                                                                      ERROR
etcd-0               Unhealthy   Get https://etcd-0:2379/health: dial tcp 192.168.112.221:2379: connect: connection refused   
scheduler            Healthy     ok                                                                                           
controller-manager   Healthy     ok                                                                                           
etcd-2               Healthy     {"health": "true"}                                                                           
etcd-1               Healthy     {"health": "true"} 
```

**Anything else we need to know?**:
Ref: https://github.com/kubernetes/kubernetes/issues/72102

**Environment**:
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.0", GitCommit:"ddf47ac13c1a9483ea035a79cd7c10005ff21a6d", GitTreeState:"clean", BuildDate:"2018-12-03T21:04:45Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.0", GitCommit:"ddf47ac13c1a9483ea035a79cd7c10005ff21a6d", GitTreeState:"clean", BuildDate:"2018-12-03T20:56:12Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"linux/amd64"}

- service-catalog version:
catalog-0.1.38.tgz, quay.io/kubernetes-service-catalog/service-catalog:v0.2.0
- Cloud provider or hardware configuration:
```shell
[root@master-1 ~]# kubectl get nodes -o wide
NAME       STATUS   ROLES    AGE     VERSION   INTERNAL-IP       EXTERNAL-IP   OS-IMAGE                KERNEL-VERSION          CONTAINER-RUNTIME
master-0   Ready    master   6d19h   v1.13.0   192.168.112.221   <none>        CentOS Linux 7 (Core)   3.10.0-862.el7.x86_64   docker://18.9.0
master-1   Ready    master   6d19h   v1.13.0   192.168.112.222   <none>        CentOS Linux 7 (Core)   3.10.0-862.el7.x86_64   docker://18.9.0
master-2   Ready    master   6d19h   v1.13.0   192.168.112.223   <none>        CentOS Linux 7 (Core)   3.10.0-862.el7.x86_64   docker://18.9.0
worker-0   Ready    <none>   6d19h   v1.13.0   192.168.112.224   <none>        CentOS Linux 7 (Core)   3.10.0-862.el7.x86_64   docker://18.9.0
worker-1   Ready    <none>   6d19h   v1.13.0   192.168.112.225   <none>        CentOS Linux 7 (Core)   3.10.0-862.el7.x86_64   docker://18.9.0
```
- Do you have api aggregation enabled? 
  - Do you see the configmap in kube-system? 
  - Does it have all the necessary fields?
    - `kubectl get cm -n kube-system extension-apiserver-authentication -o yaml` and look for `requestheader-XXX` fields
```shell
[root@master-0 service-catalog]# kubectl get cm -n kube-system extension-apiserver-authentication -o yaml | grep requestheader
  requestheader-allowed-names: '["front-proxy-client"]'
  requestheader-client-ca-file: |
  requestheader-extra-headers-prefix: '["X-Remote-Extra-"]'
  requestheader-group-headers: '["X-Remote-Group"]'
  requestheader-username-headers: '["X-Remote-User"]'
```
- Install tools:
  - Did you use helm? What were the helm arguments? Did you `--set` any extra values?
```yaml
imagePullPolicy: IfNotPresent
apiserver:
  storage:
    etcd:
      useEmbedded: false
      tls:
        enabled: true
        clientCertSecretName: catalog-etcd-secret
      servers: https://192.168.112.221:2379,https://192.168.112.222:2379,https://192.168.112.223:2379
      imagePullPolicy: IfNotPresent
      persistence:
        enabled: true
        storageClass: glusterfs-storage-class
      resources:
        requests:
          cpu: 100m
          memory: 256Mi
        limits:
          cpu: 500m
          memory: 512Mi
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 1000m
      memory: 1024Mi
controllerManager:
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 1000m
      memory: 1024Mi
```
- Are you trying to use ALPHA features? Did you enable them?
