### ISSUE TITLE
certificate signed by unknown authority while registering a test broker

### ISSUE THREAD

**Issue by yakuza-m** [kubernetes-sigs/service-catalog#2653]
# Bug Report 

**What happened**: ErrorFetchingCatalog while registering a broker

**What you expected to happen**: fetch the catalog as expected

**How to reproduce it (as minimally and precisely as possible)**: create a test broker and try to register it

Is there way to skip cert verification or any way to add this cert to trusted list please help me

**Comment by mszostok** [comment]
Hi @yakuza-m 

> create a test broker and try to register it

could you provide YAMLs that you used to install the broker?

-- 
As you can see here: https://github.com/kubernetes-sigs/service-catalog/blob/7b32d83b04d4c0f80c96841dcda3a9a009e9bb8d/contrib/examples/walkthrough/test-broker/test-servicebroker.yaml#L11-L25

by default the TLS is commented-out. So the minimal way to register the broker is to create such CR:

```
apiVersion: servicecatalog.k8s.io/v1beta1
kind: ClusterServiceBroker
metadata:
  name: test-broker
spec:
  url: http://test-broker-test-broker.test-broker.svc.cluster.local
```
