### ISSUE TITLE
Service Catalog is not compatible with k8s cluster <v1.13

### ISSUE THREAD

**Issue by vpnachev** [kubernetes-sigs/service-catalog#2678]
# Bug Report 

**What happened**:
We have a k8s cluster v1.12.10 extended with the svc-cat and a `ValidatingWebhookConfiguration` for the service catalog resources. Since service catalog `v0.1.43` whenever the webhook is called we get the following error in the catalog api server:
```
W0717 16:31:58.602774       1 dispatcher.go:73] Failed calling webhook, failing closed servicecatalog.webhook: failed calling webhook "servicecatalog.webhook": webhook does not accept v1beta1 AdmissionReviewRequest
```
Thus the request is rejected all the time.
With service-catalog `<=v0.1.42` this issue is not observed. Actually, there is an [incompatible change](https://github.com/kubernetes-sigs/service-catalog/blob/v0.1.43/vendor/k8s.io/apiserver/pkg/admission/plugin/webhook/util/client_config.go#L44-L52) introduced in `v0.1.43` which is relying on a feature available in k8s `>=v1.13`.

**What you expected to happen**:
The documentation must be updated in way that it is clear that service catalog `>=v0.1.43` is compatible only with k8s `>=v1.13`. For example [here](https://github.com/kubernetes-sigs/service-catalog/blob/master/docs/install.md) the state is that it is compatible with k8s >=`v1.9` which is not true anymore.

**How to reproduce it (as minimally and precisely as possible)**:
A `ValidatingWebhookConfiguration` like this one is required
```
apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  name: servicecatalog-admission
webhooks:
- clientConfig:
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURyekNDQXBlZ0F3SUJBZ0lRQ0R2Z1ZwQkNSckdoZFdySldaSEhTakFOQmdrcWhraUc5dzBCQVFVRkFEQmgKTVFzd0NRWURWUVFHRXdKVlV6RVZNQk1HQTFVRUNoTU1SR2xuYVVObGNuUWdTVzVqTVJrd0Z3WURWUVFMRXhCMwpkM2N1WkdsbmFXTmxjblF1WTI5dE1TQXdIZ1lEVlFRREV4ZEVhV2RwUTJWeWRDQkhiRzlpWVd3Z1VtOXZkQ0JEClFUQWVGdzB3TmpFeE1UQXdNREF3TURCYUZ3MHpNVEV4TVRBd01EQXdNREJhTUdFeEN6QUpCZ05WQkFZVEFsVlQKTVJVd0V3WURWUVFLRXd4RWFXZHBRMlZ5ZENCSmJtTXhHVEFYQmdOVkJBc1RFSGQzZHk1a2FXZHBZMlZ5ZEM1agpiMjB4SURBZUJnTlZCQU1URjBScFoybERaWEowSUVkc2IySmhiQ0JTYjI5MElFTkJNSUlCSWpBTkJna3Foa2lHCjl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUE0anZoRVhMZXFLVFRvMWVxVUtLUEMzZVF5YUtsN2hMT2xsc0IKQ1NETUFaT25UakMzVS9kRHhHa0FWNTNpalNMZGh3WkFBSUVKenM0Ymc3L2Z6VHR4UnVMV1pzY0ZzM1luRm85NwpuaDZWZmU2M1NLTUkydGF2ZWd3NUJtVi9TbDBmdkJmNHE3N3VLTmQwZjNwNG1WbUZhRzVjSXpKTHYwN0E2RnB0CjQzQy9keEMvL0FIMmhkbW9SQkJZTXFsMUdOWFJvcjVINGlkcTlKb3orRWtJWUl2VVg3UTZoTCtocWtwTWZUN1AKVDE5c2RsNmdTemVSbnR3aTVtM09GQnFPYXN2K3piTVVaQmZIV3ltZU1yL3k3dnJUQzBMVXE3ZEJNdG9NMU8vNApnZFc3alZnL3RSdm9TU2lpY05veEJOMzNzaGJ5VEFwT0I2anRTajFldFgramtNT3ZKd0lEQVFBQm8yTXdZVEFPCkJnTlZIUThCQWY4RUJBTUNBWVl3RHdZRFZSMFRBUUgvQkFVd0F3RUIvekFkQmdOVkhRNEVGZ1FVQTk1UU5WYlIKVEx0bThLUGlHeHZEbDdJOTBWVXdId1lEVlIwakJCZ3dGb0FVQTk1UU5WYlJUTHRtOEtQaUd4dkRsN0k5MFZVdwpEUVlKS29aSWh2Y05BUUVGQlFBRGdnRUJBTXVjTjZwSUV4SUsrdDFFbkU5U3NQVGZyZ1QxZVhrSW95UVkvRXNyCmhNQXR1ZFhIL3ZUQkgxakx1RzJjZW5Ubm1DbXJFYlhqY0tDaHpVeUltWk9Na1hEaXF3OGN2cE9wLzJQVjVBZGcKMDZPL25Wc0o4ZFdPNDFQMGptUDZQNmZidEdiZlltYlcwVzVCamZJdHRlcDNTcCtkV09JcldjQkFJKzB0S0lKRgpQbmxVa2lhWTRJQklxRGZ2OE5aNVlCYmVyT2dPelc2c1JCYzRMMG5hNFVVK0tyazJVODg2VUFiM0x1akVWMGxzCllTRVkxUVN0ZUR3c09vQnJwK3V2RlJUcDJJbkJ1VGhzNHBGc2l2OWt1WGNsVnpEQUd5U2o0ZHpwMzBkOHRiUWsKQ0FVdzdDMjlDNzlGdjFDNXFmUHJtQUVTcmNpSXhwZzBYNDBLUE1icDFaV1ZiZDQ9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    service:
      name: servicecatalog-admission
      namespace: default
      path: /
  failurePolicy: Fail
  name: servicecatalog.webhook
  rules:
  - apiGroups:
    - servicecatalog.k8s.io
    apiVersions:
    - v1beta1
    operations:
    - DELETE
    resources:
    - clusterservicebrokers
    - clusterserviceclasses
    - clusterserviceplans
    - serviceinstances
    - servicebindings
  sideEffects: Unknown
```

Then run the follwing command
```
$ kubectl delete servicebindings.servicecatalog.k8s.io binding
Error from server (InternalError): Internal error occurred: failed calling webhook "servicecatalog.webhook": webhook does not accept v1beta1 AdmissionReviewRequest
```

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): Server Version: v1.12.10
- service-catalog version: v0.1.43, also reproducible with v0.2.1
- Cloud provider or hardware configuration:
- Do you have api aggregation enabled? 
  - Do you see the configmap in kube-system? 
  - Does it have all the necessary fields?
    - `kubectl get cm -n kube-system extension-apiserver-authentication -o yaml` and look for `requestheader-XXX` fields
- Install tools:
  - Did you use helm? What were the helm arguments? Did you `--set` any extra values?
- Are you trying to use ALPHA features? Did you enable them?
