### ISSUE TITLE
Could not  uninstall catalog with helm2

### ISSUE THREAD

**Issue by bluven** [kubernetes-sigs/service-catalog#2778]
# Bug Report 

**What happened**:

Could not uninstall catalog, got this error:
```
Error: Job failed: BackoffLimitExceeded
```

this log is from cleaner job:
```
kubectl logs -f catalog-catalog-pre-delete-clean-job-s4xnr -n catalog
I0220 05:34:57.051409       1 hyperkube.go:192] Service Catalog version v0.3.0-beta.2 (built 2019-11-05T19:03:03Z)
Error: failed to scale down controller manager: cannot get deployment catalog/catalog-catalog-controller-manager: the server could not find the requested resource

```

**What you expected to happen**:

catalog is uninstalled

**How to reproduce it (as minimally and precisely as possible)**:

Install catalog following this [file](https://github.com/kubernetes-sigs/service-catalog/tree/v0.3.0-beta.2/charts/catalog) 

values file:
```
image: registry.bluven.me:5000/bocloud/service-catalog:v0.3.0-beta.2

apiserver:
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 100m
      memory: 128Mi
  storage:
    etcd:
      image: registry.bluven.me:5000/bocloud/etcd:v3.3.12
      resources:
        requests:
          cpu: 100m
          memory: 256Mi
        limits:
          cpu: 200m
          memory: 256Mi
controllerManager:
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 128Mi
```
The values file is used for catalog 0.2.0, I didn't changed according to 0.3.0 values.yaml, but it seems ok, anyway catalog was installed.
 
**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.3", GitCommit:"06ad960bfd03b39c8310aaf92d1e7c12ce618213", GitTreeState:"clean", BuildDate:"2020-02-11T18:14:22Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2019-12-07T21:12:17Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}

- service-catalog version:
0.3.0-beta.2
- Cloud provider or hardware configuration:
- Do you have api aggregation enabled? 
Not sure. 
  - Do you see the configmap in kube-system? 
```
➜  catalog git:(f950e68) ✗ kubectl get configmap -n kube-system
NAME                                 DATA   AGE
calico-config                        4      2d23h
catalog.v1                           1      26m
coredns                              1      2d23h
extension-apiserver-authentication   6      2d23h
kube-proxy                           2      2d23h
kubeadm-config                       2      2d23h
kubelet-config-1.17                  1      2d23h
mysql-operator.v1                    1      126m
redis-operator.v1                    1      123m
```
  - Does it have all the necessary fields?
    - `kubectl get cm -n kube-system extension-apiserver-authentication -o yaml` and look for `requestheader-XXX` fields
```
  requestheader-extra-headers-prefix: '["X-Remote-Extra-"]'
  requestheader-group-headers: '["X-Remote-Group"]'
  requestheader-username-headers: '["X-Remote-User"]'
```
- Install tools:
  - Did you use helm? What were the helm arguments? Did you `--set` any extra values?
helm2. 
- Are you trying to use ALPHA features? Did you enable them?
Basiclly default features.

**Comment by bluven** [comment]
It seems the cleaner command used AppsV1beta while the actual depolyment is under Apps/v1 api group:
```
deployment, err := c.client.AppsV1beta1().Deployments(namespace).Get(controllerName, v1.GetOptions{})
```

```
kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ template "fullname" . }}-controller-manager
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
```
