### ISSUE TITLE
Create a layer of indirection for service and plan names

### ISSUE THREAD

**Issue by arschles** [kubernetes-sigs/service-catalog#805]
#802 explains that service and plan names can change across broker catalog refreshes. Since we need a stable reference, that issue suggests using the service and plan GUID to reference services and plans in the catalog. In the SIG call on 5/8/2017, many of us agreed that there is no other option.

I agree that using GUIDs to reference services and plans on the broker is the best and most reliable. I do, however, believe that doing so is:

1. A poor user experience for the person creating new `Instance`s
2. Not portable across clusters, each of which may provide the same logical service with the same API (i.e. MySQL databases or S3-compatible object storage), but uses brokers that specify different service & plan GUIDs

To solve these two problems, I propose adding a layer of indirection (i.e. the solution to all problems in CS 😄 ) to map service-catalog service and plan names to the GUIDs.

This layer of indirection could be represented as two new resources: `ServiceName` and `PlanName`. These resources would be namespace-less (just like `ServiceClass`es and `Broker`s are right now), and look something like the following:

`ServiceName`

```yaml
apiVersion: servicecatalog.k8s.io/v1alpha1
kind: ServiceName
metadata:
    name: CoolService
spec:
    serviceGUID: fab569db-2d06-4522-b4f6-4ff06f179e5e
```

`PlanName`

```yaml
apiVersion: servicecatalog.k8s.io/v1alpha1
kind: PlanName
metadata:
    name: CoolPlan
spec:
    serviceName: CoolService # which service this is a plan of
    planGUID: 9220f523-7635-4361-86e9-f4af6a606d4f
```

Here are some considerations for these resources:

- Either the operator can manually create these or the controller can automatically create them from the original (i.e. on the first catalog fetch) names of each service & plan name.
- When a controller re-fetches a catalog from a broker, it's responsible for doing the following:
    - If the service is removed, then the corresponding `ServiceName` and all its `PlanName` resources should be "soft-deleted" (similar to the soft delete discussed in #801)
    - If the plan is removed, then the corresponding `PlanName` should be soft-deleted
    - If the service or plan GUID changed, then the corresponding GUID on the `ServiceName` or `PlanName` resource should be updated accordingly, and a new condition should be added to that `ServiceName` or `PlanName` to indicate that the update happened
